name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  ci:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Run AnyLint
        run: anylint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Run tests
        run: swift test -v
