name: CI

on:
  push:
    branches: [main, versions]
  pull_request:
    branches: [main]

jobs:
  anylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Export latest AnyLint version
        run: ::set-env name=ANYLINT_LATEST_VERSION::$( curl --silent "https://api.github.com/repos/Flinesoft/AnyLint/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' )

      - name: Export latest swift-sh version
        run: ::set-env name=SWIFT_SH_LATEST_VERSION::$( curl --silent "https://api.github.com/repos/mxcl/swift-sh/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' )
      
      - name: Use cached AnyLint
        uses: actions/cache@v1
        with:
          path: /usr/local/bin/anylint
          key: ${{ runner.os }}-anylint-$ANYLINT_LATEST_VERSION-swift-sh-$SWIFT_SH_LATEST_VERSION

      - name: Install AnyLint
        if: ${{ ! type anylint > /dev/null }}
        run: |
          git clone https://github.com/Flinesoft/AnyLint.git
          cd AnyLint
          swift build -c release
          sudo cp -f .build/release/anylint /usr/local/bin/anylint

      - name: Install swift-sh
        if: ${{ ! type swift-sh > /dev/null }}
        run: |
          git clone https://github.com/mxcl/swift-sh.git
          cd swift-sh
          swift build -c release
          sudo cp -f .build/release/swift-sh /usr/local/bin/swift-sh

      - name: Cleanup checkouts
        run: rm -rf AnyLint && rm -rf swift-sh

      - name: Run AnyLint
        run: anylint

  swiftlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v


  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v --enable-code-coverage

      - name: Report Code Coverage
        run: |
          xcrun llvm-cov export -format="lcov" .build/debug/${PACKAGE_NAME}PackageTests.xctest/Contents/MacOS/${PACKAGE_NAME}PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.lcov
        env:
          PACKAGE_NAME: AnyLint
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
