name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  swiftlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  ci:
    runs-on: macos-latest
    needs: swiftlint

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Run tests
        run: swift test
