name: Main

on:
  push:
    branches: [main]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v --enable-code-coverage

  test-windows:
    runs-on: windows-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Install Swift & Run tests
        uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift test -v
