name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs of this workflow on same branch
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  anylint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install AnyLint
        run: brew tap Flinesoft/AnyLint https://github.com/Flinesoft/AnyLint.git && brew install anylint

      - name: Run AnyLint
        run: anylint

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: swift test -v --enable-code-coverage

  # originally from: https://github.com/compnerd/swift-build/blob/master/.github/workflows/swift-argument-parser.yml
  test-windows:
    runs-on: windows-latest

    timeout-minutes: 15

    strategy:
      matrix:
        include:
          - tag: 5.4.3-RELEASE
            branch: swift-5.4.3-release

    steps:
      - uses: actions/checkout@v2

      - name: Install Swift ${{ matrix.tag }}
        run: |
          function Update-EnvironmentVariables {
            foreach ($level in "Machine", "User") {
              [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
                # For Path variables, append the new values, if they're not already in there
                if ($_.Name -Match 'Path$') {
                  $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -Split ';' | Select -Unique) -Join ';'
                }
                $_
              } | Set-Content -Path { "Env:$($_.Name)" }
            }
          }

          Install-Binary -Url "https://swift.org/builds/${{ matrix.branch }}/windows10/swift-${{ matrix.tag }}/swift-${{ matrix.tag }}-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
          Update-EnvironmentVariables
          # Reset Path and environment
          echo "$env:Path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          Get-ChildItem Env: | % { echo "$($_.Name)=$($_.Value)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append }

      - name: Run tests
        run: swift test -v
